In [1]:
import requests, time

In [2]:
standings_url = "https://fbref.com/en/comps/31/Liga-MX-Stats"

In [3]:
data = requests.get(standings_url)

In [4]:
from bs4 import BeautifulSoup

In [5]:
soup = BeautifulSoup(data.text)
standings_table = soup.select('table.stats_table')[0]
links = standings_table.find_all('a')
links = [l.get("href") for l in links]
links = [l for l in links if '/squads/' in l]

In [7]:
team_urls = [f"https://fbref.com{l}" for l in links]

In [9]:
data = requests.get(team_urls[0])

In [10]:
import pandas as pd
matches = pd.read_html(data.text, match="Scores & Fixtures")[0]

C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\4209044294.py:2: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]

In [11]:
matches

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,xG,xGA,Poss,Attendance,Captain,Formation,Opp Formation,Referee,Match Report,Notes
0,2024-07-06,21:00,Liga MX,Apertura 2024 Regular Season,Sat,Home,W,1.0,0.0,Mazatlán,2.0,0.6,65.0,15206.0,Ignacio Rivero,5-4-1,4-2-3-1,NaN,Match Report,NaN
1,2024-07-13,21:10,Liga MX,Apertura 2024 Regular Season,Sat,Away,W,4.0,0.0,Monterrey,1.9,0.4,54.0,45957.0,Ignacio Rivero,4-1-4-1,4-4-2,NaN,Match Report,NaN
2,2024-07-16,21:05,Liga MX,Apertura 2024 Regular Season,Tue,Home,W,3.0,0.0,Tijuana,2.2,0.5,39.0,NaN,Ignacio Rivero,3-4-3,4-2-3-1,NaN,Match Report,NaN
3,2024-07-20,21:05,Liga MX,Apertura 2024 Regular Season,Sat,Home,D,1.0,1.0,Toluca,1.7,0.6,67.0,NaN,Ignacio Rivero,5-3-2,4-2-3-1,NaN,Match Report,NaN
4,2024-08-23,19:00,Liga MX,Apertura 2024 Regular Season,Fri,Away,W,2.0,0.0,Querétaro,2.0,0.3,63.0,NaN,Ignacio Rivero,3-1-4-2,3-5-2,NaN,Match Report,NaN
5,2024-08-31,21:10,Liga MX,Apertura 2024 Regular Season,Sat,Home,W,4.0,1.0,América,0.9,0.7,54.0,NaN,Erik Lira,3-1-4-2,3-4-3,César Arturo Ramos,Match Report,NaN
6,2024-09-14,20:35,Liga MX,Apertura 2024 Regular Season,Sat,Away,W,2.0,1.0,León,2.0,1.3,57.0,NaN,Charly Rodríguez,3-1-4-2,4-1-2-1-2,Maximiliano Quintero,Match Report,NaN
7,2024-09-17,19:00,Liga MX,Apertura 2024 Regular Season,Tue,Away,L,1.0,3.0,Atlético,0.6,2.7,56.0,NaN,Ignacio Rivero,3-1-4-2,4-2-3-1,Oscar Mejia,Match Report,NaN
8,2024-09-21,21:05,Liga MX,Apertura 2024 Regular Season,Sat,Home,W,1.0,0.0,Guadalajara,1.9,0.8,56.0,NaN,Ignacio Rivero,5-4-1,4-1-3-2,Daniel Quintero,Match Report,NaN
9,2024-09-28,19:05,Liga MX,Apertura 2024 Regular Season,Sat,Away,W,4.0,2.0,Pachuca,2.4,1.8,70.0,NaN,Ignacio Rivero,3-1-4-2,4-1-4-1,Adonai Escobedo,Match Report,NaN
10,2024-10-05,17:00,Liga MX,Apertura 2024 Regular Season,Sat,Home,W,3.0,0.0,Necaxa,1.9,0.7,68.0,NaN,Charly Rodríguez,3-1-4-2,4-3-1-2,Guillermo Pacheco,Match Report,NaN
11,2024-10-18,21:05,Liga MX,Apertura 2024 Regular Season,Fri,Away,W,2.0,1.0,Puebla,2.4,0.4,62.0,NaN,Charly Rodríguez,3-1-4-2,5-3-2,Charles Terrazas,Match Report,NaN
12,2024-10-23,19:00,Liga MX,Apertura 2024 Regular Season,Wed,Home,W,4.0,0.0,FC Juárez,2.9,0.3,63.0,NaN,Charly Rodríguez,3-4-3,4-3-3,Vicente Arce,Match Report,NaN
13,2024-10-26,19:00,Liga MX,Apertura 2024 Regular Season,Sat,Away,NaN,NaN,NaN,UNAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Head-to-Head,NaN
14,2024-11-02,21:10,Liga MX,Apertura 2024 Regular Season,Sat,Home,NaN,NaN,NaN,Santos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Head-to-Head,NaN
15,2024-11-06,21:05,Liga MX,Apertura 2024 Regular Season,Wed,Away,NaN,NaN,NaN,Atlas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Head-to-Head,NaN
16,2024-11-09,21:05,Liga MX,Apertura 2024 Regular Season,Sat,Home,NaN,NaN,NaN,UANL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Head-to-Head,NaN

In [12]:
soup = BeautifulSoup(data.text)
links = soup.find_all('a')
links = [l.get("href") for l in links]
links = [l for l in links if l and 'all_comps/shooting/' in l]

In [13]:
links

['/en/squads/632f1838/2024-2025/matchlogs/all_comps/shooting/Cruz-Azul-Match-Logs-All-Competitions']

In [14]:
data = requests.get(f"https://fbref.com{links[0]}")

In [16]:
data

In [17]:
shooting = pd.read_html(data.text, match="Shooting")[0]

C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\2517714723.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]

In [18]:
shooting.head()

  For Cruz Azul                                                           \
           Date   Time     Comp                         Round  Day Venue
0    2024-07-06  21:00  Liga MX  Apertura 2024 Regular Season  Sat  Home
1    2024-07-13  21:10  Liga MX  Apertura 2024 Regular Season  Sat  Away
2    2024-07-16  21:05  Liga MX  Apertura 2024 Regular Season  Tue  Home
3    2024-07-20  21:05  Liga MX  Apertura 2024 Regular Season  Sat  Home
4    2024-08-23  19:00  Liga MX  Apertura 2024 Regular Season  Fri  Away

                               ... Standard             Expected               \
  Result   GF   GA   Opponent  ...     Dist FK PK PKatt       xG npxG npxG/Sh
0      W  1.0  0.0   Mazatlán  ...     18.6  0  0     0      2.0  2.0    0.12
1      W  4.0  0.0  Monterrey  ...     19.1  1  1     1      1.9  1.1    0.08
2      W  3.0  0.0    Tijuana  ...     17.1  0  0     0      2.2  2.2    0.14
3      D  1.0  1.0     Toluca  ...     16.9  1  0     0      1.7  1.7    0.08
4      W  2.0  0.0  Querétaro  ...     19.6  0  1     1      2.0  1.2    0.06

               Unnamed: 25_level_0
  G-xG np:G-xG        Match Report
0 -1.0    -1.0        Match Report
1  2.1     1.9        Match Report
2  0.8     0.8        Match Report
3 -0.7    -0.7        Match Report
4  0.0    -0.2        Match Report

[5 rows x 26 columns]

In [19]:
shooting.columns = shooting.columns.droplevel()

In [20]:
team_data = matches.merge(shooting[["Date", "Sh", "SoT", "Dist", "FK", "PK", "PKatt"]], on="Date")

In [21]:
team_data.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Opp Formation,Referee,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt
0,2024-07-06,21:00,Liga MX,Apertura 2024 Regular Season,Sat,Home,W,1.0,0.0,Mazatlán,...,4-2-3-1,NaN,Match Report,NaN,16,7,18.6,0,0,0
1,2024-07-13,21:10,Liga MX,Apertura 2024 Regular Season,Sat,Away,W,4.0,0.0,Monterrey,...,4-4-2,NaN,Match Report,NaN,14,7,19.1,1,1,1
2,2024-07-16,21:05,Liga MX,Apertura 2024 Regular Season,Tue,Home,W,3.0,0.0,Tijuana,...,4-2-3-1,NaN,Match Report,NaN,17,6,17.1,0,0,0
3,2024-07-20,21:05,Liga MX,Apertura 2024 Regular Season,Sat,Home,D,1.0,1.0,Toluca,...,4-2-3-1,NaN,Match Report,NaN,21,5,16.9,1,0,0
4,2024-08-23,19:00,Liga MX,Apertura 2024 Regular Season,Fri,Away,W,2.0,0.0,Querétaro,...,3-5-2,NaN,Match Report,NaN,22,4,19.6,0,1,1

In [22]:
years = list(range(2024, 2023, -1))
all_matches = []

In [23]:
standings_url = "https://fbref.com/en/comps/31/Liga-MX-Stats"

In [24]:
import time
for year in years:
    data = requests.get(standings_url)
    time.sleep(1)
    soup = BeautifulSoup(data.text)
    standings_table = soup.select('table.stats_table')[0]
    links = [l.get("href") for l in standings_table.find_all('a')]
    time.sleep(1)
    links = [l for l in links if '/squads/' in l]
    team_urls = [f"https://fbref.com{l}" for l in links]
    
    previous_season = soup.select("a.prev")[0].get("href")
    standings_url = f"https://fbref.com{previous_season}"
    time.sleep(1)
    
    for team_url in team_urls:
        team_name = team_url.split("/")[-1].replace("-Stats", "").replace("-", " ")
        data = requests.get(team_url)
        matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
        soup = BeautifulSoup(data.text)
        links = [l.get("href") for l in soup.find_all('a')]
        links = [l for l in links if l and 'all_comps/shooting/' in l]
        data = requests.get(f"https://fbref.com{links[0]}")
        shooting = pd.read_html(data.text, match="Shooting")[0]
        shooting.columns = shooting.columns.droplevel()
        try:
            team_data = matches.merge(shooting[["Date", "Sh", "SoT", "Dist", "FK", "PK", "PKatt"]], on="Date")
        except ValueError:
            continue
        team_data = team_data[team_data["Comp"] == "Liga MX"]
        
        team_data["Season"] = year
        team_data["Team"] = team_name
        all_matches.append(team_data)
        time.sleep(12)

C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:19: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
C:\Users\edgar\AppData\Local\Temp\ipykernel_28388\494240084.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]

In [25]:
len(all_matches)

18

In [26]:
match_df = pd.concat(all_matches)

In [27]:
match_df.columns = [c.lower() for c in match_df.columns]

In [28]:
match_df

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2024-07-06,21:00,Liga MX,Apertura 2024 Regular Season,Sat,Home,W,1.0,0.0,Mazatlán,...,Match Report,NaN,16,7,18.6,0,0,0,2024,Cruz Azul
1,2024-07-13,21:10,Liga MX,Apertura 2024 Regular Season,Sat,Away,W,4.0,0.0,Monterrey,...,Match Report,NaN,14,7,19.1,1,1,1,2024,Cruz Azul
2,2024-07-16,21:05,Liga MX,Apertura 2024 Regular Season,Tue,Home,W,3.0,0.0,Tijuana,...,Match Report,NaN,17,6,17.1,0,0,0,2024,Cruz Azul
3,2024-07-20,21:05,Liga MX,Apertura 2024 Regular Season,Sat,Home,D,1.0,1.0,Toluca,...,Match Report,NaN,21,5,16.9,1,0,0,2024,Cruz Azul
4,2024-08-23,19:00,Liga MX,Apertura 2024 Regular Season,Fri,Away,W,2.0,0.0,Querétaro,...,Match Report,NaN,22,4,19.6,0,1,1,2024,Cruz Azul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,2024-09-22,19:05,Liga MX,Apertura 2024 Regular Season,Sun,Home,W,2.0,0.0,Toluca,...,Match Report,NaN,7,4,19.4,2,0,0,2024,Santos Laguna
9,2024-09-28,21:10,Liga MX,Apertura 2024 Regular Season,Sat,Away,L,1.0,3.0,Atlético,...,Match Report,NaN,8,5,17.6,1,0,0,2024,Santos Laguna
10,2024-10-06,20:05,Liga MX,Apertura 2024 Regular Season,Sun,Home,L,0.0,2.0,FC Juárez,...,Match Report,NaN,12,4,17.6,0,0,0,2024,Santos Laguna
11,2024-10-19,19:05,Liga MX,Apertura 2024 Regular Season,Sat,Away,L,0.0,3.0,América,...,Match Report,NaN,5,3,16.4,0,0,0,2024,Santos Laguna
12,2024-10-22,19:00,Liga MX,Apertura 2024 Regular Season,Tue,Home,D,1.0,1.0,Pachuca,...,Match Report,NaN,9,5,21.1,1,0,0,2024,Santos Laguna

Obtener el los proximos partidos

In [ ]:
match_df["date"]

In [ ]:


match_df.to_csv("matchesLMX.csv")