In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [2]:
matches = pd.read_csv("matches.csv",index_col=0)

In [3]:
matches.shape

(1389, 27)

In [4]:
matches['date'] = pd.to_datetime(matches['date'])

In [5]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [6]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [7]:
matches["hour"] = matches["time"].str.replace(":.+", "" ,regex=True).astype("int")

In [8]:
matches["day_code"] = matches["date"].dt.dayofweek

In [9]:
matches["target"] = (matches["result"]=="W").astype(int)

In [10]:
rf = RandomForestClassifier(n_estimators=50,min_samples_split=10,random_state=1)
#n_estimator numero de arboles de deciono mientras > mejor precision
#min_sample_split mientras > evitas overfit, pero reduces precision
#random_state 0= mismo resultado siempre

In [11]:
train = matches[matches["date"] < '2022-01-01']
#asegurate que el test set siempre ocurra cronologicamente despues del train set

In [12]:
test = matches[matches["date"] > "2022-01-01"]

In [13]:
predictors = ["venue_code","opp_code","hour","day_code"]

In [14]:
rf.fit(train[predictors],train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [15]:
preds = rf.predict(test[predictors])

In [16]:
from sklearn.metrics import accuracy_score

In [17]:
acc = accuracy_score(test["target"],preds)

In [18]:
acc

0.6123188405797102

In [19]:
combine = pd.DataFrame(dict(actual=test["target"], predictions=preds))

In [20]:
pd.crosstab(index=combine["actual"],columns=combine["predictions"])

predictions    0   1
actual
0            141  31
1             76  28

In [21]:
from sklearn.metrics import precision_score

In [22]:
precision_score(test["target"],preds)

0.4745762711864407

In [23]:
grouped_matches = matches.groupby("team")

In [24]:
grouped_matches

In [25]:
group = grouped_matches.get_group("Manchester City").sort_values("date")

In [36]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed="left").mean()# el 3 indica cuantas semanas antes estas utilizando
    #closed = left es para que no considere datos del futuro al hacer el promedio
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)#para evitar problemas cuando estas prediciendo semana 1,2,y3 
    return group

In [37]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
5,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Home,W,1.0,0.0,Arsenal,...,5,1,2.000000,2.333333,17.333333,4.666667,18.900000,1.333333,0.333333,0.333333
7,2020-10-24,12:30,Premier League,Matchweek 6,Sat,Away,D,1.0,1.0,West Ham,...,5,0,1.333333,2.000000,17.333333,3.666667,17.733333,0.666667,0.000000,0.000000
9,2020-10-31,12:30,Premier League,Matchweek 7,Sat,Away,W,1.0,0.0,Sheffield Utd,...,5,1,1.000000,0.666667,16.666667,4.333333,18.233333,0.666667,0.000000,0.000000
11,2020-11-08,16:30,Premier League,Matchweek 8,Sun,Home,D,1.0,1.0,Liverpool,...,6,0,1.000000,0.333333,14.333333,6.666667,18.466667,1.000000,0.000000,0.000000
12,2020-11-21,17:30,Premier League,Matchweek 9,Sat,Away,L,0.0,2.0,Tottenham,...,5,0,1.000000,0.666667,12.000000,5.666667,19.366667,1.000000,0.000000,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2022-03-14,20:00,Premier League,Matchweek 29,Mon,Away,D,0.0,0.0,Crystal Palace,...,0,0,2.333333,1.333333,19.000000,7.000000,15.366667,0.333333,0.333333,0.333333
44,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Away,W,2.0,0.0,Burnley,...,5,1,1.666667,0.333333,18.333333,7.333333,16.000000,0.333333,0.000000,0.000000
46,2022-04-10,16:30,Premier League,Matchweek 32,Sun,Home,D,2.0,2.0,Liverpool,...,6,0,2.000000,0.333333,20.000000,6.666667,16.133333,0.333333,0.000000,0.000000
49,2022-04-20,20:00,Premier League,Matchweek 30,Wed,Home,W,3.0,0.0,Brighton,...,2,1,1.333333,0.666667,15.666667,4.666667,16.700000,0.333333,0.000000,0.000000
50,2022-04-23,15:00,Premier League,Matchweek 34,Sat,Home,W,5.0,1.0,Watford,...,5,1,2.333333,0.666667,15.333333,5.000000,17.200000,0.333333,0.000000,0.000000

In [38]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))
#siguente linea para futura version de pandas

C:\Users\edgar\AppData\Local\Temp\ipykernel_3172\4183442539.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [39]:
#matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols),include_groups=False)

In [40]:
matches_rolling

                                 date   time            comp         round  \
team
Arsenal                 6  2020-10-04  14:00  Premier League   Matchweek 4
                        7  2020-10-17  17:30  Premier League   Matchweek 5
                        9  2020-10-25  19:15  Premier League   Matchweek 6
                        11 2020-11-01  16:30  Premier League   Matchweek 7
                        13 2020-11-08  19:15  Premier League   Matchweek 8
...                               ...    ...             ...           ...
Wolverhampton Wanderers 32 2022-03-13  14:00  Premier League  Matchweek 29
                        33 2022-03-18  20:00  Premier League  Matchweek 30
                        34 2022-04-02  15:00  Premier League  Matchweek 31
                        35 2022-04-08  20:00  Premier League  Matchweek 32
                        36 2022-04-24  14:00  Premier League  Matchweek 34

                            day venue result   gf   ga         opponent  ...  \
team                                                                     ...
Arsenal                 6   Sun  Home      W  2.0  1.0    Sheffield Utd  ...
                        7   Sat  Away      L  0.0  1.0  Manchester City  ...
                        9   Sun  Home      L  0.0  1.0   Leicester City  ...
                        11  Sun  Away      W  1.0  0.0   Manchester Utd  ...
                        13  Sun  Home      L  0.0  3.0      Aston Villa  ...
...                         ...   ...    ...  ...  ...              ...  ...
Wolverhampton Wanderers 32  Sun  Away      W  1.0  0.0          Everton  ...
                        33  Fri  Home      L  2.0  3.0     Leeds United  ...
                        34  Sat  Home      W  2.0  1.0      Aston Villa  ...
                        35  Fri  Away      L  0.0  1.0    Newcastle Utd  ...
                        36  Sun  Away      L  0.0  1.0          Burnley  ...

                            day_code  target  gf_rolling  ga_rolling  \
team
Arsenal                 6          6       1    2.000000    1.333333
                        7          5       0    1.666667    1.666667
                        9          6       0    1.000000    1.666667
                        11         6       1    0.666667    1.000000
                        13         6       0    0.333333    0.666667
...                              ...     ...         ...         ...
Wolverhampton Wanderers 32         6       1    1.333333    1.000000
                        33         4       0    1.666667    0.666667
                        34         5       1    2.333333    1.000000
                        35         4       0    1.666667    1.333333
                        36         6       0    1.333333    1.666667

                           sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 6    7.666667    3.666667    14.733333   0.666667
                        7    5.333333    3.666667    15.766667   0.000000
                        9    7.000000    3.666667    16.733333   0.666667
                        11   9.666667    4.000000    16.033333   1.000000
                        13   9.666667    2.666667    18.033333   1.000000
...                               ...         ...          ...        ...
Wolverhampton Wanderers 32  12.333333    3.666667    19.300000   0.000000
                        33  12.333333    4.333333    19.600000   0.000000
                        34  13.000000    5.333333    19.833333   0.000000
                        35  13.000000    5.000000    18.533333   0.000000
                        36  10.000000    4.666667    17.633333   0.000000

                            pk_rolling  pkatt_rolling
team
Arsenal                 6     0.000000       0.000000
                        7     0.000000       0.000000
                        9     0.000000       0.000000
                        11    0.000000       0.000000
                        13    0.333333       0.333333
...                                ...            ...
Wolverhampton Wanderers 32    0.000000       0.000000
                        33    0.000000       0.000000
                        34    0.000000       0.000000
                        35    0.000000       0.000000
                        36    0.000000       0.000000

[1317 rows x 40 columns]

In [41]:
matches_rolling = matches_rolling.droplevel('team')

In [64]:
matches_rolling.index = range(matches_rolling.shape[0])

In [48]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, precision

In [49]:
combined, precision = make_predictions(matches_rolling,predictors + new_cols)

In [66]:
combined

,actual,predicted,date,team,opponent,result,new_team
55,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal
56,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal
57,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal
58,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal
59,1,1,2022-03-06,Arsenal,Watford,W,Arsenal
...,...,...,...,...,...,...,...
1312,1,0,2022-03-13,Wolverhampton Wanderers,Everton,W,Wolves
1313,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,L,Wolves
1314,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W,Wolves
1315,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L,Wolves
1316,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L,Wolves

In [51]:
precision

0.625

Hasta aqui es trabajo manual para mejorarlo

In [52]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [54]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [55]:
combined["new_team"] = combined["team"].map(mapping)

In [60]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [57]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

actual_x
1    27
0    13
Name: count, dtype: int64